export const UPDATE_DISHES = "UPDATE_DISHES";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_CULTURES = "UPDATE_CULTURES";
export const UPDATE_CURRENT_CULTURE = "UPDATE_CURRENT_CULTURE";
